package com.activepersistence.service.relation;

public enum ValueMethods {
   INCLUDES, EAGER_LOAD, SELECT, GROUP, ORDER, JOINS, LEFT_OUTER_JOINS, UNSCOPE, BIND,
   LIMIT, OFFSET, LOCK, READONLY, DISTINCT, REORDERING, CONSTRUCTOR,
   WHERE, HAVING, FROM
}
